git sversion = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "try-apig"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ne678a2rjy1c"
s3_prefix = "try-apig"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
