version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "try-apig"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zswqxc26ktei"
s3_prefix = "try-apig"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
