AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Tracing: Active
  Api:
    # This removes the "Stage" stage automatically created
    # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-resource-api-properties
    OpenApiVersion: 3.0.1
    TracingEnabled: true

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: my-stage
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'  # Removing single quotes will throw "Error: Failed to parse template"
          MetricsEnabled: true
          DataTraceEnabled: true
      # Running AWS::Include in DefinitionBody rather than using DefinitionUri
      # because DefinitionUri doesn't support !Sub
      # See https://github.com/awslabs/serverless-application-model/issues/305#issuecomment-562653339
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: config/apidefinition.yaml

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
