openapi: 3.0.1
info:
  version: '1.0'
  title:
    Ref: AWS::StackName
components:
  schemas:
    HelloWorldResponse:
      type: object
      required:
        - message
        - location
      properties:
        message:
          type: string
        location:
          type: string
paths:
  /hello-world:
    get:
      x-amazon-apigateway-integration:
        # HTTP method needs to be POST for custom Lambda integration, otherwise you get
        # "Unable to determine service/operation name to be authorized" at runtime
        # See https://github.com/awslabs/serverless-application-model/issues/430#issuecomment-389271807
        httpMethod: POST
        type: aws
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldFunction.Arn}/invocations
        # Sets output mapping from integration response to method response
        # Otherwise runtime throws "Execution failed due to configuration error: No match for output mapping and no default output mapping configured."
        responses:
          default:
            statusCode: '200'
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldResponse'
